[package]
name = "dummy_transactions"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strong-xml = "0.6.3"
rand = "0.8.3"
structopt = "0.3.21"
quick-xml = "0.22.0"